import "./layout.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { SessionWrapper } from "@/client-components/session-wrapper/session-wrapper";
import { getServerSession } from "next-auth";
import NavBar from "@/client-components/Nav-bar/nav-bar";
import { AppFooter } from "@/elements/app-footer/app-footer";
import { Toaster } from "react-hot-toast";
import { QueryWrapper } from "@/client-components/query-wrapper/query-wrapper";
import { Breadcrumbs } from "@/elements/breadcrump/breadcrump";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // podle potřeby
  variable: "--font-quicksand",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Daisy a. s.",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: IRootLayoutProps) {
  const session = await getServerSession();

  return (
    <html lang="en" className={`${quicksand.variable} antialiased`}>
      <body>
        <Toaster position="top-center" reverseOrder={false} />
        <SessionWrapper session={session}>
          <NavBar />

          <div className="flex flex-col items-center w-full min-h-dvh">
            <div className="w-full sm:max-w-[600px] md:max-w-[800px] lg:max-w-[1200px] p-10">
              <Breadcrumbs className="mr-auto mb-4" />
              <QueryWrapper>{children}</QueryWrapper>
            </div>
          </div>

          <AppFooter />
        </SessionWrapper>
      </body>
    </html>
  );
}
